import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `secure_settings_model.dart` with the code generated by Freezed
part 'secure_settings_model.freezed.dart';
// optional: Since our Settings class is serializable, we must add this line.
// But if Settings was not serializable, we could skip it.
part 'secure_settings_model.g.dart';

/// All settings for the app.
@freezed
class SecureSettingsModel with _$SecureSettingsModel {
  const factory SecureSettingsModel({
    required double? targetIncome,
    required DateTime? retirementDate,
  }) = _SecureSettingsModel;

  factory SecureSettingsModel.fromJson(Map<String, Object?> json) =>
      _$SecureSettingsModelFromJson(json);
}
