import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `settings.dart` with the code generated by Freezed
part 'settings.freezed.dart';
// optional: Since our Settings class is serializable, we must add this line.
// But if Settings was not serializable, we could skip it.
part 'settings.g.dart';

/// All settings for the app.
@freezed
class Settings with _$Settings {
  const factory Settings({
    required DateTime? retirementDate,
    required double? targetIncome,
    required bool? acceptTermsAndConditions,
    required bool? acceptFinancialAdviceWarning,
    required bool? welcomeScreenDismissed,
  }) = _Settings;

  factory Settings.fromJson(Map<String, Object?> json) =>
      _$SettingsFromJson(json);
}
