import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `backup_config_model.dart` with the code generated by Freezed
part 'backup_config_model.freezed.dart';
// optional: Since our BackupConfigModel class is serializable, we must add this line.
part 'backup_config_model.g.dart';

@freezed
class BackupConfigModel with _$BackupConfigModel {
  const factory BackupConfigModel({
    required DateTime backupDate,
    required String backupVersion,
  }) = _BackupConfigModel;

  factory BackupConfigModel.fromJson(Map<String, Object?> json) =>
      _$BackupConfigModelFromJson(json);
}
