import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `transfer_secure_settings_model.dart` with the code generated by Freezed
part 'transfer_secure_settings_model.freezed.dart';
// optional: Since our TransferSettingsModel class is serializable, we must add this line.
// But if Settings was not serializable, we could skip it.
part 'transfer_secure_settings_model.g.dart';

@freezed
class TransferSecureSettingsModel with _$TransferSecureSettingsModel {
  const factory TransferSecureSettingsModel({
    required DateTime? retirementDate,
    required double? targetIncome,
  }) = _TransferSecureSettingsModel;

  factory TransferSecureSettingsModel.fromJson(Map<String, Object?> json) =>
      _$TransferSecureSettingsModelFromJson(json);
}
