import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `transfer_settings_model.dart` with the code generated by Freezed
part 'transfer_settings_model.freezed.dart';
// optional: Since our TransferSettingsModel class is serializable, we must add this line.
// But if Settings was not serializable, we could skip it.
part 'transfer_settings_model.g.dart';

@freezed
class TransferSettingsModel with _$TransferSettingsModel {
  const factory TransferSettingsModel({
    required bool? acceptTermsAndConditions,
    required bool? acceptFinancialAdviceWarning,
    required bool? welcomeScreenDismissed,
    required bool optIntoAnalyticsWarning,
  }) = _TransferSettingsModel;

  factory TransferSettingsModel.fromJson(Map<String, Object?> json) =>
      _$TransferSettingsModelFromJson(json);
}
