// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm3zxECg3EPDrsOlu20F9JrUIvnC9v4Eg',
    appId: '1:125080939904:web:befbe80770910eaac12565',
    messagingSenderId: '125080939904',
    projectId: 'pensioncompare-1780a',
    authDomain: 'pensioncompare-1780a.firebaseapp.com',
    storageBucket: 'pensioncompare-1780a.appspot.com',
    measurementId: 'G-FMZ6GKB6EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKwODuvq6ZcZsT9QUZkKSlsgXvuL1KSPo',
    appId: '1:125080939904:android:fe4c89cc49aa26d1c12565',
    messagingSenderId: '125080939904',
    projectId: 'pensioncompare-1780a',
    storageBucket: 'pensioncompare-1780a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRMZd_45wqZKXlZJR3RgTPknslKonmPuE',
    appId: '1:125080939904:ios:67dea7c615ce0365c12565',
    messagingSenderId: '125080939904',
    projectId: 'pensioncompare-1780a',
    storageBucket: 'pensioncompare-1780a.appspot.com',
    iosBundleId: 'uk.co.happybunnysoftware.pensionCompare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRMZd_45wqZKXlZJR3RgTPknslKonmPuE',
    appId: '1:125080939904:ios:67dea7c615ce0365c12565',
    messagingSenderId: '125080939904',
    projectId: 'pensioncompare-1780a',
    storageBucket: 'pensioncompare-1780a.appspot.com',
    iosBundleId: 'uk.co.happybunnysoftware.pensionCompare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm3zxECg3EPDrsOlu20F9JrUIvnC9v4Eg',
    appId: '1:125080939904:web:7b53b096599bf324c12565',
    messagingSenderId: '125080939904',
    projectId: 'pensioncompare-1780a',
    authDomain: 'pensioncompare-1780a.firebaseapp.com',
    storageBucket: 'pensioncompare-1780a.appspot.com',
    measurementId: 'G-E8MN9N8F8B',
  );

}