// Mocks generated by Mockito 5.4.4 from annotations
// in pension_compare/test/app/passcode/views/change_passcode_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:pension_compare/app/passcode/controller/passcode_service.dart'
    as _i9;
import 'package:pension_compare/app/settings/controllers/settings_service.dart'
    as _i7;
import 'package:pension_compare/app/settings/models/settings.dart' as _i2;
import 'package:pension_compare/data/database/database_service.dart' as _i4;
import 'package:pension_compare/data/database/tables/pensions_with_statement.dart'
    as _i11;
import 'package:pension_compare/data/database/tables/yearly_pension_statement.dart'
    as _i12;
import 'package:shared_preferences/shared_preferences.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSettings_0 extends _i1.SmartFake implements _i2.Settings {
  _FakeSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrationStrategy_1 extends _i1.SmartFake
    implements _i3.MigrationStrategy {
  _FakeMigrationStrategy_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$PensionsTable_2 extends _i1.SmartFake
    implements _i4.$PensionsTable {
  _Fake$PensionsTable_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$StatementsTable_3 extends _i1.SmartFake
    implements _i4.$StatementsTable {
  _Fake$StatementsTable_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$OtherIncomesTable_4 extends _i1.SmartFake
    implements _i4.$OtherIncomesTable {
  _Fake$OtherIncomesTable_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SecureSettingTable_5 extends _i1.SmartFake
    implements _i4.$SecureSettingTable {
  _Fake$SecureSettingTable_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIndex_6 extends _i1.SmartFake implements _i3.Index {
  _FakeIndex_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_7 extends _i1.SmartFake
    implements _i3.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_8 extends _i1.SmartFake
    implements _i3.GeneratedDatabase {
  _FakeGeneratedDatabase_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_9 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_10 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_11 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_12 extends _i1.SmartFake
    implements _i5.StreamQueryStore {
  _FakeStreamQueryStore_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_13 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSecureSettings_14 extends _i1.SmartFake
    implements _i4.SecureSettings {
  _FakeSecureSettings_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_15 extends _i1.SmartFake implements _i3.Migrator {
  _FakeMigrator_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_16<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_17<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_18<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_19<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_20<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_21<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_22<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_23 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i7.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Settings> getAllSettings() => (super.noSuchMethod(
        Invocation.method(
          #getAllSettings,
          [],
        ),
        returnValue: _i6.Future<_i2.Settings>.value(_FakeSettings_0(
          this,
          Invocation.method(
            #getAllSettings,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Settings>);

  @override
  _i6.Future<void> saveAllSettings(_i2.Settings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAllSettings,
          [settings],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveWelcomeScreenDismissed(
    bool? welcomeScreenDismissed, [
    _i8.SharedPreferences? sharedPreferences,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWelcomeScreenDismissed,
          [
            welcomeScreenDismissed,
            sharedPreferences,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveAnalyticsSettings(
    bool? optIntoAnalyticsWarning, [
    _i8.SharedPreferences? sharedPreferences,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAnalyticsSettings,
          [
            optIntoAnalyticsWarning,
            sharedPreferences,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [PasscodeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPasscodeService extends _i1.Mock implements _i9.PasscodeService {
  MockPasscodeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isPasscodeSet() => (super.noSuchMethod(
        Invocation.method(
          #isPasscodeSet,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getEncryptedPasscode() => (super.noSuchMethod(
        Invocation.method(
          #getEncryptedPasscode,
          [],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #getEncryptedPasscode,
            [],
          ),
        ),
      ) as String);

  @override
  bool setPasscode(String? newPasscode) => (super.noSuchMethod(
        Invocation.method(
          #setPasscode,
          [newPasscode],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool changePasscode(
    String? newPasscode,
    _i4.DatabaseService? databaseService,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePasscode,
          [
            newPasscode,
            databaseService,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool validatePasscode(String? passcode) => (super.noSuchMethod(
        Invocation.method(
          #validatePasscode,
          [passcode],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<bool> testPasscode(String? passcode) => (super.noSuchMethod(
        Invocation.method(
          #testPasscode,
          [passcode],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  String encryptPasscode(String? passcode) => (super.noSuchMethod(
        Invocation.method(
          #encryptPasscode,
          [passcode],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #encryptPasscode,
            [passcode],
          ),
        ),
      ) as String);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i4.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);

  @override
  _i3.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_1(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i3.MigrationStrategy);

  @override
  _i4.$PensionsTable get pensions => (super.noSuchMethod(
        Invocation.getter(#pensions),
        returnValue: _Fake$PensionsTable_2(
          this,
          Invocation.getter(#pensions),
        ),
      ) as _i4.$PensionsTable);

  @override
  _i4.$StatementsTable get statements => (super.noSuchMethod(
        Invocation.getter(#statements),
        returnValue: _Fake$StatementsTable_3(
          this,
          Invocation.getter(#statements),
        ),
      ) as _i4.$StatementsTable);

  @override
  _i4.$OtherIncomesTable get otherIncomes => (super.noSuchMethod(
        Invocation.getter(#otherIncomes),
        returnValue: _Fake$OtherIncomesTable_4(
          this,
          Invocation.getter(#otherIncomes),
        ),
      ) as _i4.$OtherIncomesTable);

  @override
  _i4.$SecureSettingTable get secureSetting => (super.noSuchMethod(
        Invocation.getter(#secureSetting),
        returnValue: _Fake$SecureSettingTable_5(
          this,
          Invocation.getter(#secureSetting),
        ),
      ) as _i4.$SecureSettingTable);

  @override
  _i3.Index get parentPension => (super.noSuchMethod(
        Invocation.getter(#parentPension),
        returnValue: _FakeIndex_6(
          this,
          Invocation.getter(#parentPension),
        ),
      ) as _i3.Index);

  @override
  Iterable<_i3.TableInfo<_i3.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i3.TableInfo<_i3.Table, Object?>>[],
      ) as Iterable<_i3.TableInfo<_i3.Table, Object?>>);

  @override
  List<_i3.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i3.DatabaseSchemaEntity>[],
      ) as List<_i3.DatabaseSchemaEntity>);

  @override
  _i3.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_7(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i3.StreamQueryUpdateRules);

  @override
  _i3.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_8(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i3.GeneratedDatabase);

  @override
  _i3.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_9(
          this,
          Invocation.getter(#options),
        ),
      ) as _i3.DriftDatabaseOptions);

  @override
  _i3.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_10(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i3.DatabaseConnection);

  @override
  _i3.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i10.dummyValue<_i3.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_11(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i3.QueryExecutor);

  @override
  _i5.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_12(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i5.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_13(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i3.DatabaseConnectionUser);

  @override
  void setNewEncryptedPassword(String? newEncryptionPassword) =>
      super.noSuchMethod(
        Invocation.method(
          #setNewEncryptedPassword,
          [newEncryptionPassword],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Stream<List<_i4.Pension>> getAllPensions() => (super.noSuchMethod(
        Invocation.method(
          #getAllPensions,
          [],
        ),
        returnValue: _i6.Stream<List<_i4.Pension>>.empty(),
      ) as _i6.Stream<List<_i4.Pension>>);

  @override
  _i6.Future<_i4.Pension?> getPension(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getPension,
          [id],
        ),
        returnValue: _i6.Future<_i4.Pension?>.value(),
      ) as _i6.Future<_i4.Pension?>);

  @override
  _i6.Stream<_i4.Pension?> watchPension(int? id) => (super.noSuchMethod(
        Invocation.method(
          #watchPension,
          [id],
        ),
        returnValue: _i6.Stream<_i4.Pension?>.empty(),
      ) as _i6.Stream<_i4.Pension?>);

  @override
  _i6.Future<_i4.Pension?> createPension(
    String? name,
    DateTime? maturityDate,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPension,
          [
            name,
            maturityDate,
            notes,
          ],
        ),
        returnValue: _i6.Future<_i4.Pension?>.value(),
      ) as _i6.Future<_i4.Pension?>);

  @override
  _i6.Future<int> updatePension(
    int? id,
    String? name,
    DateTime? maturityDate,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePension,
          [
            id,
            name,
            maturityDate,
            notes,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> deletePension(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePension,
          [id],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> doesPensionNameExist(
    int? id,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #doesPensionNameExist,
          [
            id,
            name,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Stream<List<_i4.Statement>> getAllStatementsForPension(int? pensionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllStatementsForPension,
          [pensionId],
        ),
        returnValue: _i6.Stream<List<_i4.Statement>>.empty(),
      ) as _i6.Stream<List<_i4.Statement>>);

  @override
  _i6.Future<_i4.Statement?> getStatement(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getStatement,
          [id],
        ),
        returnValue: _i6.Future<_i4.Statement?>.value(),
      ) as _i6.Future<_i4.Statement?>);

  @override
  _i6.Future<_i4.Statement?> createStatement(
    int? pensionId,
    DateTime? statementDate,
    double? planValue,
    double? projectedAnnualAmount,
    double? yearlyCharges,
    double? transferValue,
    double? amountPaidIn,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStatement,
          [
            pensionId,
            statementDate,
            planValue,
            projectedAnnualAmount,
            yearlyCharges,
            transferValue,
            amountPaidIn,
            notes,
          ],
        ),
        returnValue: _i6.Future<_i4.Statement?>.value(),
      ) as _i6.Future<_i4.Statement?>);

  @override
  _i6.Future<bool> updateStatement(
    int? id,
    int? pensionId,
    DateTime? statementDate,
    double? planValue,
    double? projectedAnnualAmount,
    double? yearlyCharges,
    double? transferValue,
    double? amountPaidIn,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatement,
          [
            id,
            pensionId,
            statementDate,
            planValue,
            projectedAnnualAmount,
            yearlyCharges,
            transferValue,
            amountPaidIn,
            notes,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> deleteStatement(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteStatement,
          [id],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> doesStatementDateExist(
    int? id,
    int? pensionId,
    DateTime? statementDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #doesStatementDateExist,
          [
            id,
            pensionId,
            statementDate,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i4.OtherIncome?> getStatePension() => (super.noSuchMethod(
        Invocation.method(
          #getStatePension,
          [],
        ),
        returnValue: _i6.Future<_i4.OtherIncome?>.value(),
      ) as _i6.Future<_i4.OtherIncome?>);

  @override
  _i6.Future<_i4.OtherIncome?> saveStatePension(
    double? annualAmount,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStatePension,
          [
            annualAmount,
            notes,
          ],
        ),
        returnValue: _i6.Future<_i4.OtherIncome?>.value(),
      ) as _i6.Future<_i4.OtherIncome?>);

  @override
  _i6.Stream<List<_i4.OtherIncome>> getAllOtherIncomes() => (super.noSuchMethod(
        Invocation.method(
          #getAllOtherIncomes,
          [],
        ),
        returnValue: _i6.Stream<List<_i4.OtherIncome>>.empty(),
      ) as _i6.Stream<List<_i4.OtherIncome>>);

  @override
  _i6.Stream<_i4.SecureSettings> getSecureSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSecureSettings,
          [],
        ),
        returnValue: _i6.Stream<_i4.SecureSettings>.empty(),
      ) as _i6.Stream<_i4.SecureSettings>);

  @override
  _i6.Future<_i4.SecureSettings> saveSecureSettings(
    double? targetIncome,
    DateTime? retirementDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSecureSettings,
          [
            targetIncome,
            retirementDate,
          ],
        ),
        returnValue:
            _i6.Future<_i4.SecureSettings>.value(_FakeSecureSettings_14(
          this,
          Invocation.method(
            #saveSecureSettings,
            [
              targetIncome,
              retirementDate,
            ],
          ),
        )),
      ) as _i6.Future<_i4.SecureSettings>);

  @override
  _i6.Stream<List<_i11.PensionWithStatement>>
      getAllPensionsWithLatestStatement() => (super.noSuchMethod(
            Invocation.method(
              #getAllPensionsWithLatestStatement,
              [],
            ),
            returnValue: _i6.Stream<List<_i11.PensionWithStatement>>.empty(),
          ) as _i6.Stream<List<_i11.PensionWithStatement>>);

  @override
  _i6.Stream<List<_i12.YearlyPensionStatement>> getYearlyPensionSummary() =>
      (super.noSuchMethod(
        Invocation.method(
          #getYearlyPensionSummary,
          [],
        ),
        returnValue: _i6.Stream<List<_i12.YearlyPensionStatement>>.empty(),
      ) as _i6.Stream<List<_i12.YearlyPensionStatement>>);

  @override
  _i6.Future<void> populateTestData() => (super.noSuchMethod(
        Invocation.method(
          #populateTestData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i3.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_15(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i3.Migrator);

  @override
  _i6.Future<void> beforeOpen(
    _i3.QueryExecutor? executor,
    _i3.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<T> createStream<T extends Object>(
          _i5.QueryStreamFetcher<T>? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i6.Stream<T>.empty(),
      ) as _i6.Stream<T>);

  @override
  T alias<T, D>(
    _i3.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i10.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<Set<_i3.TableUpdate>> tableUpdates(
          [_i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i6.Stream<Set<_i3.TableUpdate>>.empty(),
      ) as _i6.Stream<Set<_i3.TableUpdate>>);

  @override
  _i6.Future<T> doWhenOpened<T>(
          _i6.FutureOr<T> Function(_i3.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_16<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i6.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
          _i3.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_17<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
          _i3.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_18<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_19<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_20<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.Selectable<_i3.TypedResult> selectExpressions(
          Iterable<_i3.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeSelectable_21<_i3.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i3.Selectable<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
          _i3.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_22<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i3.DeleteStatement<T, D>);

  @override
  _i6.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i6.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
      ) as _i6.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_21<_i3.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_21<_i3.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i3.Selectable<_i3.QueryRow>);

  @override
  _i6.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<T> transaction<T>(
    _i6.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_16<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i6.Future<T>);

  @override
  _i6.Future<T> exclusively<T>(_i6.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_16<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i6.Future<T>);

  @override
  _i6.Future<void> batch(_i6.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_23(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_23(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i3.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);
}
