// Mocks generated by Mockito 5.4.4 from annotations
// in pension_compare/test/app/passcode/views/set_passcode_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:pension_compare/app/passcode/controller/passcode_service.dart'
    as _i6;
import 'package:pension_compare/app/settings/controllers/settings_service.dart'
    as _i3;
import 'package:pension_compare/app/settings/models/settings.dart' as _i2;
import 'package:pension_compare/data/database/database_service.dart' as _i8;
import 'package:shared_preferences/shared_preferences.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSettings_0 extends _i1.SmartFake implements _i2.Settings {
  _FakeSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i3.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Settings> getAllSettings() => (super.noSuchMethod(
        Invocation.method(
          #getAllSettings,
          [],
        ),
        returnValue: _i4.Future<_i2.Settings>.value(_FakeSettings_0(
          this,
          Invocation.method(
            #getAllSettings,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Settings>);

  @override
  _i4.Future<void> saveAllSettings(_i2.Settings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAllSettings,
          [settings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveWelcomeScreenDismissed(
    bool? welcomeScreenDismissed, [
    _i5.SharedPreferences? sharedPreferences,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWelcomeScreenDismissed,
          [
            welcomeScreenDismissed,
            sharedPreferences,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveAnalyticsSettings(
    bool? optIntoAnalyticsWarning, [
    _i5.SharedPreferences? sharedPreferences,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAnalyticsSettings,
          [
            optIntoAnalyticsWarning,
            sharedPreferences,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [PasscodeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPasscodeService extends _i1.Mock implements _i6.PasscodeService {
  MockPasscodeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isPasscodeSet() => (super.noSuchMethod(
        Invocation.method(
          #isPasscodeSet,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getEncryptedPasscode() => (super.noSuchMethod(
        Invocation.method(
          #getEncryptedPasscode,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getEncryptedPasscode,
            [],
          ),
        ),
      ) as String);

  @override
  bool setPasscode(String? newPasscode) => (super.noSuchMethod(
        Invocation.method(
          #setPasscode,
          [newPasscode],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool changePasscode(
    String? newPasscode,
    _i8.DatabaseService? databaseService,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePasscode,
          [
            newPasscode,
            databaseService,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool validatePasscode(String? passcode) => (super.noSuchMethod(
        Invocation.method(
          #validatePasscode,
          [passcode],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<bool> testPasscode(String? passcode) => (super.noSuchMethod(
        Invocation.method(
          #testPasscode,
          [passcode],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  String encryptPasscode(String? passcode) => (super.noSuchMethod(
        Invocation.method(
          #encryptPasscode,
          [passcode],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #encryptPasscode,
            [passcode],
          ),
        ),
      ) as String);
}
